language: node_js
node_js:
- 8.11.3
cache:
  yarn: true
  directories:
  - node_modules
  - client/node_modules
  - server/node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
- export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
  - stage: Test, Build and Deploy
    branch:
      on:
      - master
      - dev
    script:
    - yarn test
    - yarn build
    deploy:
      provider: heroku
      app: cowcowcow
      api_key:
        secure: 
deploy:
  api_key:
    secure: MFN18NupPppDem9JXd8GrE4YUdTZ/w/crYtczxZUKt/+VRdCFSAlht6ee8RFFcIdMGQjx7FZIo8uOmsWSUzDNYaFB8tohVqV2C8RFUIEDTbXksjJX+o8nH9orO9KLDuSJnOsGSbj1krmH6LptRW5/+ceW1cGiSKxT0V5YhrUta/VF0Nx1zg/NtI4/HBqORofGF0waER1RFk3QvhVvnItQhePPID5iR2q5DtI8+hP/h+mXJOiOTRnTsatds94KwlTMcCW2O+ULuTx8KnZ397tE6dub4Ki6O/c7/q351+ahs1f6s6GQytzDJvRX9/CScIpOy3aHSABENHqMeDXKeMj2AkT0S0MoRXs9UN4Tz5GbWzzhKmIcAAJOOC4eD9mJjWNpqTaj/FG3YbTswjReny+auyZZJvdT0YLKKcG6rZBCV6QNFAvmwOMI3TbmvbQFvKIu0vaG7ICQy4GY5OQiTS+IWU4M4AgUR2UqTW6gxpWbs7KdMufSP22B8Qqi4PpqZWJpFACXQi3JmqZBTwgthvv0zYM3r5CZsBkHXftrDeSBYMwDJiPNERVNLzn/aGAawUR0gXcK9PY4FdervHRtObVVXjT0RLSQZpwssc6VBWHm0+IAHec8Uk4MBiSBD2nh/GiqMnYa3pvFQzzMsKEH6nPnINrfOLxfNPaQAwoHuZj8HY=
